tasks/urls.py
from django.urls import path
from .views import Tasks, remove_from_todolist, update_task

app_name = "tasks"

urlpatterns = [
    path('', Tasks, name='tasks'),
    path('/<str:pk>', update_task, name="update_task"),
    path('/<str:pk>', remove_from_todolist, name="remove_from_todolist"),

]

todo_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasks.urls'))
]

tasks/models.py
from django.db import models


class Todolist(models.Model):
    task = models.CharField(max_length=100)
    completed = models.BooleanField(default=False)

    def __str__(self):
        return self.task

tasks/forms.py
from django import forms
from django.forms import ModelForm
from .models import Todolist


class TodolistForm(forms.ModelForm):
    task = forms.CharField(max_length=100)

    class Meta:
        model = Todolist
        fields = '__all__'

tasks/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .models import *
from .forms import *


def Tasks(request):
    tasks = Todolist.objects.all()
    if request.method == 'POST':
        form = TodolistForm(request.POST)
        if form.is_valid():
            new_task = form.cleaned_data.get('task')
            create_task = Todolist(task=new_task)
            create_task.save()
            return redirect("/")
    else:
        form = TodolistForm()

    context = {
        'tasks': tasks,
        'form': form
    }
    return render(request, 'task_list.html', context)


def update_task(request, pk):
    task = Todolist.objects.get(id=pk)
    form = TodolistForm(instance=task)
    if request.method == 'POST':
        form = TodolistForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            return redirect("/")

    context = {
        'form': form
    }
    return render(request, "update.html", context)


def remove_from_todolist(request, pk):
    item = get_object_or_404(Todolist, id=pk)
    if item:
        item.delete()
        return redirect("/")
    else:
        return redirect("/")

templates/task_list.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<style>

	body{
		background-color: #638CB8;
	}

	input{
		width: 100%;
		padding: 12px 20px;
		margin: 8px 0;
		box-sizing: border-box;
	}

	input::placeholder {
	  color: #d3d3d3;
	}

	.submit{
		background-color: #6BA3E8;
	}

	.center-column{
		width:600px;
		margin: 20px auto;
		padding:20px;
		background-color: #fff;
		border-radius: 3px;
		box-shadow: 6px 2px 30px 0px rgba(0,0,0,0.75);
	}

	.item-row{
		background-color: #906abd;
		margin: 10px;
		padding: 20px;
		border-radius: 3px;
		color: #fff;
		font-size: 16px;
		box-shadow: 0px -1px 10px -4px rgba(0,0,0,0.75);
	}

	.btn-danger{
		background-color: #ffae19;
		border-color: #e59400;
	}

</style>

<div class="center-column">
    <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-primary">Add Task</button>
    </form>

    {% for task in tasks %}
    <div class="item-row">
        <div class="item-row">
            <a class="btn btn-sm btn-info" href="{% url 'tasks:update_task' task.id %}">Update</a>
            <a class="btn btn-sm btn-danger" href="{% url 'tasks:remove_from_todolist' task.id %}">Delete</a>

            {% if task.completed == True %}
            <strike>{{task}}</strike>
            {% else %}
            <span>{{task}}</span>
            {% endif %}
        </div>
    </div>
    {% endfor %}
</div>

templates/update.html
<h3>UPDATE TASK</h3>

<form action="" method="post">
  {% csrf_token %}
  {{ form }}
  	<input type="submit" name="Update Task">
</form>